#!/usr/bin/php -q
<?php
/**
 * EBText is a tool for sending and receiving SMS trough SMS Server
 * Tools v3
 * 
 * @author	Erick Birbe <erickcion@gmail.com>
 * @date	2015-09-04
 * */

/* *********************************************************************
 * VALIDATIONS... neccessary to run well
 * ********************************************************************/

// Verify the arguments before continue
if (!isset($argv) or count($argv) < 3)
{
	echo "Nothing to do here... I quit!\n";
	return 1;
}

// Set the current directory correctly for CLI requests
if (defined('STDIN'))
{
	chdir(dirname(__FILE__));
}

/* ********************************************************************
 * MAIN PROCESS
 * ********************************************************************/
require_once('ebtmessage.php');
require_once('eventhandler/ebtmsgreceived.php');

function run($event, $file, $id = NULL)
{
	switch($event)
	{
		case 'RECEIVED':
			$oMgsRcvd = new EBTMsgReceived($file);
			$oMgsRcvd->execute();
			break;

		case 'SENT':
			break;

		case 'FAILED':
			break;

		case 'REPORT':
			break;

		case 'CALL':
			break;

		default:
			break;
	}
}

$sms_event = $argv[1];
$sms_filename = $argv[2];
$sms_id = isset($argv[3]) ? $argv[3] : NULL;

// Start the applicantion
run($sms_event, $sms_filename, $sms_id);
